services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    volumes:
      - ./frontend/frontend:/app
    depends_on:
      - backend

  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
